name: Unit Tests

on:
  push:
    branches: [ main ]
  pull_request:

permissions:
  contents: read

jobs:
  test-native:
    name: Run Native Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v6
        with:
          submodules: true

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y cmake gcc make

      - name: Configure CMake
        working-directory: test
        run: cmake -B build -S .

      - name: Build tests
        working-directory: test
        run: cmake --build build -- -j$(nproc)

      - name: Run tests with CTest
        working-directory: test/build
        run: ctest --output-on-failure